version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: dev
    command: npx nodemon --watch src --watch public --exec "node --enable-source-maps src/server.js"
    volumes:
      - ./:/usr/src/app:cached
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true