version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: character-app:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      retries: 3